version: 2

env:
  - GO111MODULE=on
builds:
  - main: main.go
    binary: jasongen
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz

nfpms:
  - package_name: jasongen
    vendor: Jason Hancock
    homepage: https://github.com/jasonhancock/jasongen
    maintainer: Jason Hancock <jason@jasonhancock.com>
    description: jasongen openapi code generator
    formats:
      - deb
    bindir: /usr/bin
    epoch: 1
    release: 1


brews:
  - name: jasongen
    repository:
      owner: jasonhancock
      name: homebrew-jasonhancock

    commit_author:
      name: goreleaserbot
      email: jason@jasonhancock.com

    folder: formula
    homepage: "https://github.com/jasonhancock/jasongen"
    description: "jasongen openapi code generator"

    install: |
      bin.install "jasongen"
